### PR TITLE
coverage

### PR DESCRIPTION
**Pull request by PDhanrajnath**

### CODE REVIEW

**Review by rohithZE — COMMENTED** [review]
scanner work files are pushed to git
please checl

**Comment by PDhanrajnath** [comment]
yes Rohith
I have added .scannerwork in .gitignore file

**Comment by rohithZE** [comment]
> yes Rohith I have added .scannerwork in .gitignore file

if you have pushed scannerwork first and then added gitignore then it wont work
you will have to manually delete the files

**Comment by PDhanrajnath** [comment]
I'll do that Rohith

**Pull request merged**
